# Throttle bandwidth
# https://github.com/unisoncomputing/nimbus/issues/130
delay_pools 1
delay_class 1 1
delay_access 1 allow all
# The syntax here is refill rate (bytes per second) followed by bucket size.
# So 1000000/500000000 is a 500MB bucket that refills at 1 MB per second.
# This allows for bursts while limiting overall bandwidth.
delay_parameters 1 1000000/500000000
